### ISSUE TITLE
redSqrt error

### ISSUE THREAD

**Issue by fanatid** [indutny/bn.js#101]
On testing https://github.com/cryptocoinjs/secp256k1-node/pull/57 [Martin Becze](http://github.com/wanderer/) found that [elliptic](http://github.com/indutny/elliptic) and secp256k1-node embedded pure js implementation have error on recover operation.
* Message: f75c6b18a72fabc0f0b888c3da58e004f0af1fe14f7ca5d8c897fe164925d5e9
* Signature: fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd03641408887321be575c8095f789dd4c743dfe42c1820f9231f98a962b210e3ac2452a3
* Recovery ID: 0

But the real problem with [redSqrt](https://github.com/indutny/bn.js/blob/e82b88e2f11fe22c75f62b434d2f841e7fd619c6/lib/bn.js#L2805):
```js
var BN = require('bn.js')
var n = new BN('16e5f9d306371e9b876f04025fb8c8ed10f8b8864119a149803357e77bcdd3b1', 'hex').toRed(BN.red('k256'))
console.log(n.redSqr().redSqr().cmp(n))
```
give 1 instead 0

It's can be easily solving in bn.js by comparing result with [redSqr](https://github.com/indutny/bn.js/blob/e82b88e2f11fe22c75f62b434d2f841e7fd619c6/lib/bn.js#L2792) and throwing error... but how resolve it in elliptic context?
@indutny any ideas?

cc: @wanderer

**Comment by indutny** [comment]
I'm not quite sure what you meant @fanatid . This sample: https://gist.github.com/indutny/38322b0b42eccd94d4e4 shows that red is producing the same number as if it would be computed without it... Do you think this is a bug in bn.js?

Where is the problem and what is expected result?

**Comment by fanatid** [comment]
Oh, sorry, I skipped **t** in code... right version:
```js
var BN = require('bn.js')
var n = new BN('16e5f9d306371e9b876f04025fb8c8ed10f8b8864119a149803357e77bcdd3b1', 'hex').toRed(BN.red('k256'))
console.log(n.redSqrt().redSqr().cmp(n))
```

**Comment by indutny** [comment]
Oh, this changes everything!

**Comment by indutny** [comment]
@fanatid it looks like this number may not have square root module secp256k1. Is it expected to have recovery id equal to `0`? Or is `0` the result that it reports?

May I ask you to help me and submit the test case for elliptic?

**Comment by fanatid** [comment]
As I understand it was random data. What you want to see in PR? Test data for secp256k1 with quadratic nonresidue number?

**Comment by indutny** [comment]
How have you discovered the error in first place? :) I guess the test case may use some precomputed data as from the issue description, and it should demonstrate that the computation goes wrong using elliptic.

I will figure out the best way to fix this problem from there. Thank you!

**Comment by fanatid** [comment]
Martin report me that elliptic and embedded not throwing error on some data, but bitcoin/secp256k1 does. I checked bitcoin/secp256k1 and found that error throwing from sqrt operation, than checked js implementations. [bitcoin/secp256k1 sqrt](https://github.com/bitcoin/secp256k1/blob/c18b869e58aa4d3bff6958f370f6b643d1223c44/src/field_impl.h#L123)

**Comment by indutny** [comment]
Yeah, I got this. I just need a regression test case for elliptic. Going to handle this problem there.

**Comment by indutny** [comment]
Fixed this in elliptic, please consider updating to 6.2.1, hope it helps!

**Comment by fanatid** [comment]
Fedor, did you also seen `redSqrt` in `_getEndoRoots` in short curve? `cmp` with will be faster than `redSub`, but any case it works as expected, thank you!

**Comment by indutny** [comment]
@fanatid I seen it, but I don't care that much about it right now. This code is not really used a lot, since endo roots are cached for all supported curves.
