### ISSUE TITLE
RFC: parseBase/toString for radixes outside 2/10/16 (maybe even 8)

### ISSUE THREAD

**Issue by axic** [indutny/bn.js#107]
Does any other base than 2/10/16 (and maybe even 8) make any sense in day to day usage? Is there any use case for them today? The current implementation forces a single hardcoded alphabet consisting of 0-9,a-z,A-Z cut off at the radix. 

Wouldn't it make more sense for those to support a user-supplied alphabet, similarly to the way [base-x](https://github.com/cryptocoinjs/base-x) does it?

**Comment by indutny** [comment]
I think it should probably work for any bases from 1 to 36 as for regular JS numbers.

**Comment by indutny** [comment]
IMO, user supplied alphabet does not make sense, never heard about this sort of API in any serious big number library.

**Comment by axic** [comment]
I hope you are aware that the alphabet varies between big integer libraries.

`gmp` (used by node-bigint):
> For base in the range 2..36, digits and lower-case letters are used; for -2..-36, digits and upper-case letters are used; for 37..62, digits, upper-case letters, and lower-case letters (in that significance order) are used.

`openssl` (used by `node-bignum` aka `bignum`):
parser only supports base 2, 10 and 16, and toString only supports 10 and 16

`bignumber.js`:
> For bases from 10 to 36, lower and/or upper case letters can be used to represent values from 10 to 35.
> For bases above 36, a-z represents values from 10 to 35, A-Z from 36 to 61, and $ and _ represent 62 and 63 respectively (this can be changed by editing the ALPHABET variable near the top of the source file).

`sjcl`:
only supports base 2, 10, 16, 32, 64. Base 64 is the well known base64 alphabet.

`bn.js`:
compared to the above, given that `bn.js` is limited to <= base-36, the alphabet usage matches that of `bignumber.js`

**Comment by indutny** [comment]
Ok, I was a bit wrong then. Anyway, I don't feel like it is justified. Performance-wise it will mean a lot slower code. 3rd-party libraries could take `toArray` output and convert it to requested base if needed.

**Comment by indutny** [comment]
Sorry, closing the issue.
