### ISSUE TITLE
GCD of negative number + zero

### ISSUE THREAD

**Issue by axic** [indutny/bn.js#110]
In the tests we have ```assert.equal(new BN(-18).gcd(new BN(12)).toString(16), '6');``` thus allowing negative numbers as an input.

For ```new BN(-18).gcd(new BN(0))``` we get -18, where GCD should be a positive number?

The same applies to ```new BN(0).gcd(new BN(-18))```.

If allowing gcd over a negative number is desired, the simple fix is to call `iabs()` here:
```js
  BN.prototype.gcd = function gcd (num) {
    if (this.isZero()) return num.clone();
    if (num.isZero()) return this.clone();
  ...
```

**Comment by indutny** [comment]
Sounds like a bug to me.

**Comment by axic** [comment]
This is fixed now
