### ISSUE TITLE
modn API inconsistency

### ISSUE THREAD

**Issue by axic** [indutny/bn.js#112]
All mod/div methods return a BN instance, except `modn` which returns a JS Number.

I think it would make sense making the current `modn` internal (prefixing it with _) so that `toString` can keep using it the fastest way, and creating a new `modn` which returns a BN instance.

`divmod` already encapsulates a `modn` result as a BN instance so it should use the new method.

Comments?

**Comment by indutny** [comment]
I'm fine with fixing it, but let's postpone it until next major release.

**Comment by axic** [comment]
When do you plan a new major release? Should this live in a branch until then? Or shouldn't we have a branch called `v5.x` so changes like that can be merged in there?

**Comment by indutny** [comment]
Hm... I'm not sure about it yet. Do you think there is some urgency in handling this particular issue? Or do you have any other plans in mind?

**Comment by axic** [comment]
Don't know, there could be a couple of things made more clear, etc.

- Renaming strip() to _strip() is a breaking change too (https://github.com/indutny/bn.js/pull/105)
- Maybe reviewing the constructor method(s) could lead to such a change (see https://github.com/indutny/bn.js/pull/91)

**Comment by jprichardson** [comment]
According to https://github.com/indutny/bn.js#postfixes, any method ending with `n` returns a JavaScript `number`. Why change that here? Wouldn't that be confusing? ping @calvinmetcalf

**Comment by indutny** [comment]
@jprichardson this is not exactly true. `n` applies only to argument, it does not say anything about return value. For example `.iaddn` returns `BN`.

**Comment by jprichardson** [comment]
> n - which means that the argument of the function must be a plain JavaScript number

@indutny Gahhh. Haha, it says "argument" right there - sorry I missed that.

**Comment by axic** [comment]
All the arithmetic methods return a BN except `modn`. Perhaps it could be a good idea to agree on a prefix or suffix for those which don't and have that as a counterpart for `modn` after the breaking change?

**Comment by indutny** [comment]
I can't really think about anything other than `rn`? Like `returns number`.
