### ISSUE TITLE
.cmp() can return -0

### ISSUE THREAD

**Issue by axic** [indutny/bn.js#125]
```js
new BN(-42).cmp(new BN(-42)) // -0
```

This line is the cause: https://github.com/indutny/bn.js/blob/master/lib/bn.js#L2768

It is not a major issue per se, as -0 == 0 in Javascript, thus comparing the output with 0 will return true.

**Comment by fanatid** [comment]
@axic :+1: 
Should be `if (this.negative !== 0 && res !== 0) return -res`

**Comment by axic** [comment]
Also the same applies to `.cmpn()`

**Comment by dcousens** [comment]
Good find

**Comment by Yaffle** [comment]
https://github.com/indutny/bn.js/issues/3
