### ISSUE TITLE
Extra hands

### ISSUE THREAD

**Issue by indutny** [indutny/bn.js#132]
@dcousens @calvinmetcalf

I just wanted to ask you guys if you would be interested in becoming maintainers for this library? Not that  I'm not going to review PRs, but it looks like you have lots of feedback that is driven by your needs, and usually provide very relevant suggestions.

If it works for you - I will give you permissions here and on npm.

(@axic don't be offended, you are next on this queue! Just give it some time :) I want to make sure that we synchronize our view on this library)

**Comment by calvinmetcalf** [comment]
sure I can do that

**Comment by indutny** [comment]
@calvinmetcalf done (I assume you are `cwmma` on npm). Thank you!

**Comment by calvinmetcalf** [comment]
yes thats me thanks

**Comment by indutny** [comment]
No, thank **you**!

**Comment by dcousens** [comment]
@indutny :+1:

I'm happy too take this up,  I generally always wait for a release ACK from another contributor so I'm sure @calvinmetcalf and I can balance it like we have for most of the browserify code.

**Comment by indutny** [comment]
And done, thank you everyone!
