### ISSUE TITLE
& 0x3ffffff in _parseHex

### ISSUE THREAD

**Issue by dchest** [indutny/bn.js#139]
In `_parseHex`:

```javascript
      this.words[j] |= (w << off) & 0x3ffffff;
      this.words[j + 1] |= w >>> (26 - off) & 0x3fffff;
```

That's

```
0x3ffffff
0x3fffff
```
I believe the second one should be `0x3ffffff` (2^26-1) as well.

**Comment by fanatid** [comment]
I think there all fine, 0x3ffffff is 26 bits, 0x3fffff is 24: 26 + 24 = 48 / 8 = 6 bytes

**Comment by indutny** [comment]
Yeah, seems to be fine to me too. Thank you, though!

(Thanks @fanatid , that was quick!)

**Comment by dchest** [comment]
Ah, ok, sorry.

**Comment by fanatid** [comment]
just working on new feature for bn.js ATM :smile:

**Comment by indutny** [comment]
Added comment for you 4240f12 !

**Comment by dchest** [comment]
@indutny nice

**Comment by dcousens** [comment]
@indutny maybe make the two constants... constant variables?

**Comment by indutny** [comment]
@dcousens not that I mind, but we are not using ES6 in this library. And regular `var CONST_SOMETHING = ...` resulted in low-quality generated code (last time I checked it).

**Comment by indutny** [comment]
`const value = ...` works like a charm in ES6, though. So if we will eventually move to it - it should be one of the first things to do.

**Comment by dcousens** [comment]
:+1:
