### ISSUE TITLE
idea: comb10MulTo as function from string

### ISSUE THREAD

**Issue by fanatid** [indutny/bn.js#143]
We can replace [comb10MulTo](https://github.com/indutny/bn.js/blob/4240f12f72def5b3659300aea44ef9b5aa4e4b2b/lib/bn.js#L1035) by function from string:
```js
var f = new Function('a', 'b', 'return a + b')
console.log(f(1, 2)) // 3
```
i.e. instead this big function we put generator.

**Comment by indutny** [comment]
This won't work in Chrome App Store, and other sandboxed JS environments which do not support any form of `eval`.

**Comment by fanatid** [comment]
but is it `eval`? I say about [function constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function)

**Comment by indutny** [comment]
It is kind of the same thing as `eval`, just in a different flavor. It still evaluates code from the string dynamically.

See: https://developer.chrome.com/extensions/sandboxingEval

**Comment by fanatid** [comment]
@indutny thank you for link
