### ISSUE TITLE
Math.imul possible issue

### ISSUE THREAD

**Issue by axic** [indutny/bn.js#144]
The fast 256bit multiplication uses Math.imul if available: https://github.com/indutny/bn.js/blob/master/lib/bn.js#L1606:

There was a bug in webkit (Safari 7.0.x) where Math.imul returned wrong results in certain cases: https://bugs.webkit.org/show_bug.cgi?id=126345

Emscripten still has the following check to avoid it:

```
// check for imul support, and also for correctness ( https://bugs.webkit.org/show_bug.cgi?id=126345 )^M
if (!Math['imul'] || Math['imul'](0xffffffff, 5) !== -5) Math['imul'] = function imul(a, b) {
  var ah  = a >>> 16;
  var al = a & 0xffff;
  var bh  = b >>> 16;
  var bl = b & 0xffff;
  return (al*bl + ((ah*bl + al*bh) << 16))|0;
};
Math.imul = Math['imul'];
```

Would it make sense checking for: `!Math.imul || Math.imul(0xffffffff, 5) === -5)` ?

I understand it is the browser for a 2.5 year old operating system, but we're talking about cryptography here which shouldn't return off results.

@fanatid could the imul code trigger the above issue?

**Comment by fanatid** [comment]
@axic bn.js uses maximum 13 bits numbers in `Math.imul`, this bug touched only `0xffffffff, 5`?

**Comment by axic** [comment]
@fanatid I'm not sure, the bugzilla isn't really descriptive and I'm not familiar with webkit source code. Came across this while working with Emscripten and thought it might be relevant.

**Comment by indutny** [comment]
I believe it should not affect bn.js, as webkit's commit says:

```
 Don't truncate non-int doubles to 0 -- that's just not how ToInt32 works.
 Instead, take a slow path that will do the right thing.
```

Clearly bn.js is using small numbers that are always integers.

Thanks for the heads up, though!

**Comment by axic** [comment]
@indutny I believe Math.imul is integer only. That commit log refers to how it is implemented internally in webkit.

**Comment by indutny** [comment]
@axic that commit says that `Math.imul` didn't work on doubles. While it implicitly converts inputs to integers, they doesn't have to be such.

**Comment by axic** [comment]
`Math.imul(0xffffffff, 5)` was the one triggering the bug, that doesn't seem like a double. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul states:
> Math.imul() allows for fast 32-bit integer multiplication with C-like semantics.

**Comment by indutny** [comment]
yeah, exactly.
