### ISSUE TITLE
number is null on initialization

### ISSUE THREAD

**Issue by fanatid** [indutny/bn.js#145]
What is the point in this [condition in constructor](https://github.com/indutny/bn.js/blob/9d0d0e33fa523935660870dfb5fde36ea42d0ad3/lib/bn.js#L33)?

**Comment by indutny** [comment]
* https://github.com/indutny/bn.js/blob/9d0d0e33fa523935660870dfb5fde36ea42d0ad3/lib/bn.js#L316
* https://github.com/indutny/bn.js/blob/9d0d0e33fa523935660870dfb5fde36ea42d0ad3/lib/bn.js#L316
* and some other places

It is used to create empty `BN` instance to pre-populate it later.

**Comment by fanatid** [comment]
@indutny what about creating method `.empty()` for this?
```js
var EC = require('elliptic').ec
var ec = new EC('secp256k1')
var keys = ec.keyFromPrivate()
console.log(keys.derive(ec.genKeyPair().getPublic()))
// => TypeError: Cannot read property '0' of null
```
it happens because curve tried multiply point by secret that equal to null (to be precise, multiply by BN initialized with null)
of course `elliptic` also should prevent this cases... but initializing BN with zero by default would be more safety?

**Comment by indutny** [comment]
Mmm... And how would `.empty()` work? The whole point is that `new BN(null)` should be very very fast.

**Comment by fanatid** [comment]
Yes, I understand that constructing BN for `.copy` should be fast. IDK how `.empty()` could work, probably this method is impossible for implementation :)

**Comment by indutny** [comment]
Exactly! 👍 

If you will ever have it working, I'd be more than happy to land it.

**Comment by axic** [comment]
@fanatid based on the code:
- `new BN(null)` should return an empty instance
- `new BN(0)` and `new BN()` should return a zero initialised one

You have to explicitly include `null` as an argument.

Are you sure something isn't missing in `elliptic`?

**Comment by fanatid** [comment]
@axic `elliptic` shouldn't allow
- create `KeyPair` from undefined private key (`ec.keyFromPrivate()`)
- call `.derive` if `KeyPair` doesn't have private key

the problem is that `.derive` pass `null` to `Point.mul` that convert argument to BN and then call `.bitLength()` that throwing error

I open issue here only because creating empty BN for null is not good way? Why not NaN, Infinity? Zero should be by default? IDK

**Comment by indutny** [comment]
Yikes. I'd say this is a bug in `elliptic`
