### ISSUE TITLE
BN parses invalid characters

### ISSUE THREAD

**Issue by kumavis** [indutny/bn.js#151]
bn = new BN('xxx', 16)
<BN: 888>

**Comment by flyswatter** [comment]
Yeah, I just ran into this, took a long time to debug, because I assumed hex-prefixed base 16 would be digested gracefully.

```
> var a = new BN('0x01', 16)
undefined
> a
<BN: 801>
```

Hex prefixes should be removed automatically, and otherwise invalid characters should throw a descriptive error.

**Comment by fanatid** [comment]
related with #141 
unfortunately that PR don't fix this issue

**Comment by flyswatter** [comment]
If it throws an error for the hex prefix, I'd consider that mostly solving the issue.  Wouldn't the `x` trigger an error in that PR?

**Comment by fanatid** [comment]
@flyswatter I already checked and looks like that PR don't throw error
as I understand it is happens because #141 fix `_parseBase`, but when base equal 16 `_parseHex` is used..

**Comment by axic** [comment]
Also: #90 & #91 (#91 actually implements the fix)

**Comment by kumavis** [comment]
Just ran in to this again omg fml

**Comment by dcousens** [comment]
@kumavis wrap the BN constructor in something that is stricter so as to avoid this issue.
