### ISSUE TITLE
Documentation for `isBN()` says it's a BN object method

### ISSUE THREAD

**Issue by alanmimms** [indutny/bn.js#155]
The documentation for `isBN()` says it's a method on `a` - it shows the function as `a.isBN(object)`. This cannot be true since the whole _point_ of the `isBN(object)` function is to determine if `object` is a `BN.js` object.

It should be shown as `BN.isBN(object)` instead, which matches the actual implementation.

**Comment by dcousens** [comment]
Submit a PR?

**Comment by dcousens** [comment]
Closing in favour of #156
