### ISSUE TITLE
-n suffix behavior

### ISSUE THREAD

**Issue by Zanibas** [indutny/bn.js#161]
Currently, the definition of -n suffix behavior is that it can accept a plain JS number in its parameters. However, if we were to use say:

```
var a = new BN(1e4)
a.muln(2.55)
```

The expected answer is not produced. I understand that the documentation says that the library does not support decimal notation, but there's an ambiguity in the statement that -n suffix functions can accept plain JS numbers.

Could we get clarification on the expected behavior in this scenario? Should decimals still not be supported in this case or could this behavior theoretically work in this library?

**Comment by kumavis** [comment]
yeah i think this would require some backwards carry which is not implemented
https://github.com/indutny/bn.js/blob/master/lib/bn.js#L1892-L1914

**Comment by kumavis** [comment]
if the intent is to not support it, please add that note by the -n suffix doc

**Comment by indutny** [comment]
This library works only with integers. As readme says, no decimals are ever allowed anywhere.

"Plain JS number" means that you don't have to create `new BN(123)` big integer, and may just use `123` itself.

**Comment by kumavis** [comment]
Here is a PR to add a note to the n-suffix section of the readme https://github.com/indutny/bn.js/pull/162
