### ISSUE TITLE
BN make Fusebox bundler optimizer to fail

### ISSUE THREAD

**Issue by Janaka-Steph** [indutny/bn.js#169]
Hello,

I am using Fusebox bundler and this code bellow is making the optimizer Quantum to fail.

```
 try {
    // Obfuscate that we require Buffer, to reduce size
    Buffer = require('buf' + 'fer').Buffer;
  } catch (e) {
  }
```

I don't know if you can fix it in bn.js or if I should fix it with Fusebox, but I open the issue to let you know.

**Comment by calvinmetcalf** [comment]
this is likely an issue with fusebox so you may want to open an issue there

**Comment by indutny** [comment]
I think I'm going to land this soon: https://github.com/indutny/bn.js/pull/168 . Should be fixed by then.
