### ISSUE TITLE
Constructor strips trailing zeroes in Little Endian

### ISSUE THREAD

**Issue by gnarula** [indutny/bn.js#175]
I'm not sure if this is the intended behaviour but it really seemed inconsistent with the rest of the API and took a while to figure this out in a downstream project.

```js
const BN = require("bn.js");
let a = new BN("000a", 16, "le");
console.log(a.toArray("le")); // [10]
let b = new BN([0, 10], 16, "le");
console.log(b.toArray("le")); // [0, 10]
```

**Comment by dcousens** [comment]
@gnarula reading https://github.com/indutny/bn.js/blob/98ac84e81dc02d178168460e5889c80840853a44/lib/bn.js#L76-L97

`parseHex` does not support little endian hex,  at all.
It is treating your input as big endian.

**Comment by dcousens** [comment]
@indutny maybe conflicting arguments should throw?
