### ISSUE TITLE
In-place operation in a reduction context is not reduced.

### ISSUE THREAD

**Issue by mahrud** [indutny/bn.js#177]
Seems like in-place operations are not reducing the result before changing the host object. Example:
```
var BN=require('bn.js')
red = new BN.red(new BN(13))
a = new BN(2).toRed(red)
b = new BN(7).toRed(red)
x = a.redIMul(b)

red.m // <BN: d>
x // <BN-R: 1>
x.cmp(red.m) // correct
a // <BN-R: e>
a.cmp(red.m) // incorrect
```
Note that `a` is still in a reduction context, but its value is larger than the modulus!

**Comment by fanatid** [comment]
This happens because `Red#imod` is not actually `imod`... :( https://github.com/indutny/bn.js/blob/98ac84e81dc02d178168460e5889c80840853a44/lib/bn.js#L3172

**Comment by dcousens** [comment]
Closing in favour of #178
