### ISSUE TITLE
Decimal handling with div arithmatic

### ISSUE THREAD

**Issue by GeeeCoin** [indutny/bn.js#182]
How does the `.div()` method handle decimals?

**Comment by indutny** [comment]
It doesn't, this library is for integers.

**Comment by GeeeCoin** [comment]
My apologies, I meant how does it handle fractional output? I'm assuming it truncates the return value.

**Comment by fanatid** [comment]
@GeeeCoin you can use `.divmod`, in this case you receive result and remainder

**Comment by GeeeCoin** [comment]
@fanatid thanks. Given that we're dealing with Wei, the least significant digit is inconsequential anyway, but good to know.

**Comment by jtakalai** [comment]
Following worked for me:
```
function e(x, n) { 
  base = new BN(10).pow(new BN(n));
  dm = new BN(x).divmod(base);
  return dm.div + "." + dm.mod.toString(10, n)
}

e(10000, 3) // === "10.000"
```

Not sure if there is a library function already?

**Comment by chuckbergeron** [comment]
> Following worked for me:
> ...
> function e(x, n) { 
> ...
> Not sure if there is a library function already?

Just a heads-up, the function above will only support lower numbers on the right-hand side. In other words 10000 / 3 is fine, but if you're working with something like Wei in Ethereum your BN's are going to be around 1000000000000000000 and the function will pin your CPU and cause an out of memory exception.

**Comment by PaulRBerg** [comment]
FWIW, I ended up creating my own unit mapping:

```javascript
const unitMapping = {
  "0": "noether",
  "1": "wei",
  "3": "kwei",
  "6": "mwei",
  "9": "gwei",
  "12": "microether",
  "15:": "milliether",
  "18": "ether",
  "21": "kether",
  "24": "mether",
  "27": "tether",
};
```

I also have a function that takes the ERC20 decimals as input and defaults to "ether" if the value is not found in the mapping. Suboptimal, but better than assuming that all tokens have 18 decimals.
