### ISSUE TITLE
DEP0079: Custom inspection function on Objects via .inspect()

### ISSUE THREAD

**Issue by fanatid** [indutny/bn.js#184]
https://github.com/indutny/bn.js/blob/98ac84e81dc02d178168460e5889c80840853a44/lib/bn.js#L359-L361

Now this is deprecated: https://nodejs.org/api/deprecations.html#deprecations_dep0079_custom_inspection_function_on_objects_via_inspect

Any thought how we can resolve it? Require `util` is not a option, right?

**Comment by takahser** [comment]
I'm having the same issue. When `console.log`ing a `BN` object, it would display the following warning:

**(node:50542) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated**

**Comment by GaddMaster** [comment]
It's like I'm disallowed console log objects anymore ???
