### ISSUE TITLE
Inconsistent results with max safe integer

### ISSUE THREAD

**Issue by ltfschoen** [indutny/bn.js#197]
The largest max safe integer in JavaScript is `9007199254740991` (equivalent to `2**53-1`).
```
> new BN(9007199254740991)
<BN: 1fffffffffffff>

> new BN(9007199254740992)
Error: Assertion failed
```

When I try to convert the max safe integer to BN and then back to Number it works successfully. And when I try to convert an unsafe integer (i.e. `2**53`) it works correctly by returning an error.

```
> (2**53)-1
9007199254740991

> (new BN('2').pow(new BN('53'))).sub(new BN('1')).toNumber()
9007199254740991

> (new BN('2').pow(new BN('53'))).toNumber()
Error: Number can only safely store up to 53 bits
```

Now the value `9*10**15 < (2**53)-1` returns true (i.e. `9000000000000000 < 9007199254740991`, since 9*10**15 is a safe number.

```
> 9*10**15
9000000000000000
```

But when I try to express that value using BN, and then convert it back to a Number **it returns an error, which I was not expecting**, instead of `9000000000000000` as I expected it to.

```
> (((new BN('9')).mul(new BN('10'))).pow(new BN('15'))).toNumber()
Error: Number can only safely store up to 53 bits

> (((new BN('9')).mul(new BN('10'))).pow(new BN('15'))).toString(10)
'205891132094649000000000000000'
```

I was going to use this technique to allow users to enter scientific notation on a website and convert it to BN.js (i.e. if a user entered a string value of '9e15' then I would process it as above, where the 'e' would be interpreted as the `.mul(new BN('10'))` part). 

I want to do it this way to avoid bugs in my code. For instance I accidentally passed the scientific notation value as a string instead of a number and got unintended results.

```
new BN('9e15').toNumber()
10415
```

When it should have been:

```
> new BN(9e15).toNumber()
9000000000000000

> new BN(9.007199254740992e15).toNumber()
Error: Assertion failed
```

**Comment by Yaffle** [comment]
Seems, you need to calculate `9*(10**15)`, not `(9*10)**15`:
```
-(((new BN('9')).mul(new BN('10'))).pow(new BN('15'))).toNumber()
+new BN('9').mul(new BN('10').pow(new BN('15'))).toNumber()
```
