### ISSUE TITLE
little-endian constructor ignoring important zeroes

### ISSUE THREAD

**Issue by igormcoelho** [indutny/bn.js#208]
I noticed that constructor is ignoring important zeroes on little-endian constructor.
Example:
```js
x = new BN('0000ff', 16, 'le')
<BN: ff>   // should be  <BN: ff0000>
x = new BN('010000ff', 16, 'le')
<BN: ff000001>
```

**Comment by amaurymartiny** [comment]
Same here:

`new BN('0001000000000000', 'hex', 'le').toNumber()`

Expected: 256
Got: 1

**Comment by mahnunchik** [comment]
Hi, @indutny current version of bn.js completely ignores leading zeroes in `le` notation. 

`elliptic` is effected to because it uses `bn.js` under hood: https://github.com/indutny/elliptic/blob/e71b2d9359c5fe9437fbf46f1f05096de447de57/lib/elliptic/utils.js#L115-L117

Example of incorrect multiplication:
```js
const ec = new EdDSA('ed25519');
const k = ec.decodeInt('0000000000000000000000000000000000000000000000000000000000000001');
const K = elliptic.utils.encode(ec.encodePoint(ec.g.mul(k), 'hex'));
```

**Comment by fanatid** [comment]
I'll look into this shortly.

**Comment by mahnunchik** [comment]
I'm looking forward to have `elliptic` lib updated to use fixed `bn.js` 👀

**Comment by fanatid** [comment]
Released in 5.2.0

**Comment by mahnunchik** [comment]
I think https://github.com/indutny/elliptic should be updated to latest bn.js.

**Comment by fanatid** [comment]
Ah, I'll release 4.12.0 tomorrow for elliptic. Thanks that pointed on this!

**Comment by fanatid** [comment]
4.12.0 is published.
