### ISSUE TITLE
BN mul

### ISSUE THREAD

**Issue by geghamjivanyan** [indutny/bn.js#210]
I have 2 32-byte length BN objects - bn1 and bn2. 
bn = bn1.mul(bn2);
bn.length = 64

Is it possible to multiply 2 BN's without changing length as it works in C++, Python etc?

**Comment by fanatid** [comment]
This is not possible with `bn.js`..
can you explain how this possible in python?

**Comment by geghamjivanyan** [comment]
Python is a wrapper of C++ code. So if anything is possible, then it is possible in C++. For example OpenSSL lib  https://github.com/openssl/openssl. 

And now I have a compatibility problem between Python and JS due to BN size.

**Comment by fanatid** [comment]
When Python become wrapper of C++ code?

If you want stay with same length of number you can apply `.mod` after multiplication. Of course this will be slower than just multiplication with specific length, but this will works.

**Comment by geghamjivanyan** [comment]
When Python become wrapper of C++ code? I mean Python lib which I use for BN is a wrapper of C++ Lib.

**Comment by geghamjivanyan** [comment]
It is worked with .mod. Thanks
