### ISSUE TITLE
Precision loss on division

### ISSUE THREAD

**Issue by isaacsultan** [indutny/bn.js#213]
I am receiving a result of <BN: 0> when dividing two large numbers.

# Usage

```
const a = new BN(500).mul(new BN(10).pow(new BN(18))) // 500e18
const b = new BN(500).mul(new BN(10).pow(new BN(18))) // 500e18
const c =  a.div(b)

console.log(c) ->  <BN: 0>
```

# System information

* npm 6.5.0
* node v8.9.3
* bn.js 4.11.6

**Comment by Yaffle** [comment]
cannot reproduce with node v10.5.0 on Windows x64:
<BN: 1>

**Comment by W3stside** [comment]
bumping this as I am seeing the same thing - 

```
const divisor = toBN('10').pow(toBN('18'))

toBN("444547505974302564").div(divisor).toString() // "0"
("444547505974302564" / 10**18).toString() // "0.4445475059743026"
```
```
npm 6.5.0
node v10.7.0
bn.js 4.11.6
```

**Comment by indutny** [comment]
Hello everyone!

Sorry for delay. As mentioned in readme:

```
Note: decimals are not supported in this library.
```

This is an *integer* only library and does not support floating point operations.
