### ISSUE TITLE
Implement fromNumber()

### ISSUE THREAD

**Issue by cliffhall** [indutny/bn.js#223]
I'm amazed that there is no easy way to create a BN from a JavaScript number without converting that number to a string and using the BN constructor, like:
`const my BN = new BN(Number(90125).toString(), 10);`

Instead, I'd like to do something like:
`const myBN = BN.fromNumber(90125)`

**Comment by fanatid** [comment]
Do you mean from `Number` which `Object`?
```js
> typeof new Number(123)
'object'
```

**Comment by cliffhall** [comment]
@fanatid No. I mean there is no functionality for creating a new BN from a Number. The BN constructor takes a string and a radix. Therefore I have to convert a number to a string before I can create a new BN with it. And unless I missed it, there's no utility function for taking a JavaScript Number and returning a equivalent BN instance.

**Comment by fanatid** [comment]
Actually, it's possible..

```js
> new BN(42).muln(2)
BN { negative: 0, words: [ 84 ], length: 1, red: null }
```

https://github.com/indutny/bn.js/blob/f953de2a4040852c8948f6ac36e501b092379292/lib/bn.js#L39
https://github.com/indutny/bn.js/blob/f953de2a4040852c8948f6ac36e501b092379292/lib/bn.js#L77-L79
https://github.com/indutny/bn.js/blob/f953de2a4040852c8948f6ac36e501b092379292/lib/bn.js#L113-L141

**Comment by cliffhall** [comment]
@fanatid When I try to put a number into the constructor like:
`const withdrawal = new BN(accounting.calcNet(itemAmount, franchiseFeePercent) * 2);`

I get: 
![Screen Shot 2019-07-27 at 5 14 50 PM](https://user-images.githubusercontent.com/871933/61999570-1ffe8b00-b092-11e9-9dc9-eeedece1ce80.png)

**Comment by cliffhall** [comment]
@fanatid I'm proposing a function along the lines of this:

```
BN.fromNumber = function(jsNum) {
  
  return typeof jsNum === "number" ? new BN(jsNum.toString(), 10) : null;

}
```

**Comment by fanatid** [comment]
Number `32642567254300000` is unsafe, because this error raised.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER
```js
> 32642567254300000 <= Number.MAX_SAFE_INTEGER
false
```

What we actually need this is better error message, not new function.

**Comment by cliffhall** [comment]
A better error message would be good, but the new function would keep people from having to convert numbers to strings before constructing a BN. If there was a fromNumber, people would likely use it and never encounter the error condition. Also better documentation would help.

**Comment by fanatid** [comment]
While functions for creating BN from string/number/etc probably would be helpful, I do not think that will be changed. BN used in too much things and if tomorrow major version will be released with functions which should be used instead constructor thousands packages will need change code a lot.
I do not think that converting unsafe numbers implicitly in BN is correct thing. If people want create BN from unsafe numbers they should do this in their code, otherwise at one day somebody will blame BN that precision was lost here.

PR's for better error messages / documentations is highly welcome!
