### ISSUE TITLE
Incorrect division result

### ISSUE THREAD

**Issue by SylTi** [indutny/bn.js#228]
BN.js version: ^4.11.5
from web3 version: 1.0.0-beta.52

Exemple: 
```
const BN = web3.utils.toBN;
console.log("BN('1682000').div(BN('2030000000')=", BN('1682000').div(BN('2030000000')).toString());
console.log("BN('1682000', 8).div(BN('2030000000', 8)=", BN('1682000', 8).div(BN('2030000000', 8)).toString());
```

Result: 
```
BN('1682000').div(BN('2030000000')= 0
BN('1682000', 8).div(BN('2030000000', 8)= 0
```

Expected:
`BN('1682000').div(BN('2030000000')= 828571`

**Comment by fanatid** [comment]
Expected `1682000 / 2030000000 = 828571` ?

**Comment by SylTi** [comment]
with a base decimal point at 8? yeah.
Otherwise, it's `1682000 / 2030000000 = 0.00082857142`
But that's still not 0.

**Comment by SylTi** [comment]
it's like doing 0.01682 / 20.3 = 0.00082857142
since `0.01682 * 10**8 = 1682000` & `20.3 * 10**8 = 2030000000`

**Comment by fanatid** [comment]
bn.js works only with integers... maybe `divmod` will help you:
```js
const BN = require('bn.js');
const conv = (bn) => `(div = ${bn.div.toString()}, mod = ${bn.mod.toString()})`
console.log("BN('1682000').div(BN('2030000000')=", conv(new BN('1682000').divmod(new BN('2030000000'))));
console.log("BN('1682000', 8).div(BN('2030000000', 8)=", conv(new BN('1682000', 8).divmod(new BN('2030000000', 8))));
```
result:
```
BN('1682000').div(BN('2030000000')= (div = 0, mod = 1682000)
BN('1682000', 8).div(BN('2030000000', 8)= (div = 0, mod = 492544)
```

**Comment by SylTi** [comment]
Then I'm kind of missing the point of having the possibility to specify the number of decimals if I can't get a valid result when dividing two number with the same number of decimals? 
Because this give me the correct result: 
```
console.log("BN('1682000', 8).div(BN('2030000000', 8)=", BN('1682000', 8).mul(BN(10**9)).div(BN('2030000000', 8)).toString());
console.log("BN('1682000').div(BN('2030000000')=", BN('1682000').mul(BN(10**9)).div(BN('2030000000')).toString());
```

result: 
```
BN('1682000', 8).div(BN('2030000000', 8)= 828571
BN('1682000').div(BN('2030000000')= 828571
```

Which seems to me could should done automatically when dividing two number with the same number of decimals by doing something like
```
if (a.decimals == b.decimals)
 return a*10**(decimals+1).div(b);
```

**Comment by fanatid** [comment]
Sorry, I can not understand your point :confused:

From last comment... I'm I understand that under `BN('1682000', 8)` you mean BN instance with 8 decimals? If so, bn.js do not support decimals and second argument here is base.

**Comment by SylTi** [comment]
Then I completely misunderstood the doc. My bad.
