### ISSUE TITLE
Problem with typescript

### ISSUE THREAD

**Issue by stefdelec** [indutny/bn.js#230]
` Module '"/someproject/node_modules/@types/bn.js/index"' can only be default-imported using the 'esModuleInterop' flag

import BN from "bn.js";`

You should `import * as BN from 'bn.js`' 
`export default BN;`
to be more typescript friendly in your interface.

**Comment by fanatid** [comment]
But this repo not contain any ts definitions and package too, how we can fix it? Probably you should create issue in ts definitions collection repo?

**Comment by stefdelec** [comment]
Ok. I thought you were publishing yourself the declaration files.

Thanks for your quick answer. I close the issue.

**Comment by stefdelec** [comment]
FYI https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...stefdelec:patch-4
