### ISSUE TITLE
jsbn.isProbablePrime() alternative ?

### ISSUE THREAD

**Issue by stasbar** [indutny/bn.js#246]
Hello,
I'm rewriting my library from [jsbn](https://github.com/andyperlitch/jsbn) to bn.js, but I'm missing the [.isProbablePrime()](https://github.com/andyperlitch/jsbn/blob/52fab097bf5fe2ad981be3d5f22b97032811c6a7/index.js#L1582) function. Does bn.js offer the alternative? Or do I have to write myself ?

**Comment by indutny** [comment]
Hello!

You could give a try to https://github.com/indutny/primal .

Hopefully it helps!
