### ISSUE TITLE
Include a LICENSE.txt file in the repo

### ISSUE THREAD

**Issue by gavingmiller** [indutny/bn.js#250]
To make searching for the repository's license a bit easier, can a specific LICENSE.txt (or LICENSE.md) be added to repo?

This is also falls in line with GitHub's best practices: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#determining-the-location-of-your-license

**Comment by indutny** [comment]
Sure thing! Feel free to open a PR for that! Thanks!
