### ISSUE TITLE
Why do the read functions say they take in type `BN`?

### ISSUE THREAD

**Issue by SurienDG** [indutny/bn.js#257]
Example:
When I try to do `redSub(b: BN): RedBN` it with a regular `BN` for `b` it gives me an error that says `Error: red works only with red numbers`.

So shouldn't the input type here be `RedBN` not `BN`?

![image](https://user-images.githubusercontent.com/18398584/101105655-1ba68400-359c-11eb-9154-44fb5f0f54b0.png)

**Comment by fanatid** [comment]
Is this from some TS definition? If so, please contact the author of these definitions because we do not provide them.
