### ISSUE TITLE
muln with fractional number gives wrong result 

### ISSUE THREAD

**Issue by mahnunchik** [indutny/bn.js#276]
`muln` method gives wrong result using fractional number for numbers up to `67108864`.

```js
new BN('67108864', 10).muln(0.5)
// actial 0
// expected 33554432
```
Numbers less than `67108864` works as expected:

```js
new BN('67108863', 10).divn(2)
// 33554431
```

**Comment by mahnunchik** [comment]
@indutny @fanatid please have a look at this issue

**Comment by Yaffle** [comment]
@mahnunchik , I don't think fractional numbers are supported by this library, try new BN(0.5).toString()

**Comment by fanatid** [comment]
Fractional numbers are not supported.
