### ISSUE TITLE
can you please check division?

### ISSUE THREAD

**Issue by Yaffle** [indutny/bn.js#28]
new BN("6582018229284824168619876730229320890292528855852623664389292032").div(new BN("730750818665451459101842416358132502628711530497")).toString() 

result of truncated divison should be equal to "9007199254740991"

**Comment by indutny** [comment]
Oh gosh... :) Looks like I broke it. Thanks!

**Comment by indutny** [comment]
Should be fixed by d40d7d9. Turned out to be totally unrelated to division. Thanks again!
