### ISSUE TITLE
Converting json.stringified BN back into BN

### ISSUE THREAD

**Issue by 0xCactus** [indutny/bn.js#283]
Applied `JSON.stringify` on BN which gave me `{"_bn":{"negative":0,"words":[22127744,7770787,46556922,61120705,33815569,32632618,19307227,5865125,41554856,1514719,0],"length":10,"red":null}}`. Any idea how I may convert this back into an instance of BN?

**Comment by fanatid** [comment]
You serialize `BN` as `String` in `JSON.stringify` and create a new `BN` from `String` in `JSON.parse`.

**Comment by 0xCactus** [comment]
> You serialize `BN` as `String` in `JSON.stringify` and create a new `BN` from `String` in `JSON.parse`.

@fanatid JSON.parse converts it to an object of `{"_bn":{"negative":0,"words":[22127744,7770787,46556922,61120705,33815569,32632618,19307227,5865125,41554856,1514719,0],"length":10,"red":null}}` without the BN class method. I tried passing the object into `new BN(object)` but the BN created is off from the original BN

**Comment by acnebs** [comment]
Seeing this too. Test case:

```js
const bigNum = new BN(Number(90125));
console.log(bigNum.toString(10)); // 90125

const rebuiltNum = new BN(JSON.parse(JSON.stringify(bigNum)))
console.log(rebuiltNum.toString(10)); // 16013
```
