### ISSUE TITLE
setn function signature in index.tx doesn't correspond with the library

### ISSUE THREAD

**Issue by israel-gonzalezmedina** [indutny/bn.js#289]
Hi. I am kind of new with typescript. I want to use the library, specifically the setn(index, value) but the editor shows me that the signature is senth(index) which is the signature in index.d.ts. In javascript code works like charm. but when use it with typescritp da error.
maybe is something I need to do.
Any help please

**Comment by fanatid** [comment]
This repo does not have TypeScript bindings, please re-create the issue in the correct repo.
https://www.npmjs.com/package/@types/bn.js
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bn.js
