### ISSUE TITLE
BN.muln with number bigger than 0x4000000

### ISSUE THREAD

**Issue by youPickItUp** [indutny/bn.js#306]
BN.muln throws when called with number bigger than 0x4000000

I haven't came across this information until it has blown up on a website :cry: 

I wanted to make sure it's true and ask for some warning / info in the README / docs.
I can do the PR just let me know if that's correct.

**Comment by fanatid** [comment]
This is expected, internally BN operates 26 bits numbers, so you need to use `mul`
https://github.com/indutny/bn.js/blob/5df40f81ea8afb835b909bb7c21e0833cdeb6a30/lib/bn.js#L1993
