### ISSUE TITLE
We need a Logo.

### ISSUE THREAD

**Issue by hemanth** [indutny/bn.js#33]
![befunky_bn png](https://cloud.githubusercontent.com/assets/18315/6107547/e1bf8308-b091-11e4-948b-abda9fbce552.png)

@indutny I'm not all that great in making logos, just gave it try, not that good.

 Maybe @stoeffel can help...

**Comment by stoeffel** [comment]
I will try to create something tomorrow. Sry, I have no time today :smile:

**Comment by indutny** [comment]
Yay, thanks a lot guys!

**Comment by stoeffel** [comment]
My first try.
It's pretty simple though.
![bn](https://cloud.githubusercontent.com/assets/1217681/6122947/b9f862da-b0fb-11e4-8951-9828645ef829.png)

**Comment by hemanth** [comment]
@stoeffel May be a horizontal logo with `<bn: js>` in it?

**Comment by indutny** [comment]
@stoeffel what does `3n` mean? I see that it looks quite similar to `Bn`, but why `3n`? :)

**Comment by stoeffel** [comment]
Was a quick shot :smile:  I am working on something else.

**Comment by stoeffel** [comment]
How about something like this?
![bn2](https://cloud.githubusercontent.com/assets/1217681/6127818/9e7d4172-b12f-11e4-9c2c-197192de1899.png)

Maybe with the text proposed from @hemanth `<bn: js>`?

**Comment by stoeffel** [comment]
@indutny the `3` should be a `B` :smile:

**Comment by stoeffel** [comment]
* better simple logo

![bn3](https://cloud.githubusercontent.com/assets/1217681/6129119/22f45a24-b13c-11e4-84b0-63612156d095.png)

**Comment by indutny** [comment]
Hah, let's go with latter one.

**Comment by stoeffel** [comment]
https://github.com/stoeffel/bn.js.logo here you go

**Comment by stoeffel** [comment]
Will you add it to the readme or should I create a PR?

**Comment by indutny** [comment]
PR, please! ;)

**Comment by hemanth** [comment]
![](http://www.reactiongifs.com/r/omsj.gif)
