### ISSUE TITLE
make cmp easy to work with

### ISSUE THREAD

**Issue by wanderer** [indutny/bn.js#39]
what do you think about added `eq`, `gte`, `lte`, `gt`, `lt` to the API? Each of these method would return a `bool`. Code get messy fast if you have a bunch of `cmp`s

**Comment by indutny** [comment]
@wanderer I'm a bit afraid of blowing up the library's size. Are you sure that it is hard to deal with bn.js without these? I wrote ECDSA library on top of bn.js without actually suffering from using the `.cmp()`.

**Comment by wanderer** [comment]
Ok, I can appreciate minimalism
