### ISSUE TITLE
power mod

### ISSUE THREAD

**Issue by wanderer** [indutny/bn.js#40]
How can I do a `powm` ?

**Comment by indutny** [comment]
I think it is available as the part of Reduction context (red), please take
a look at .redPow()

**Comment by wanderer** [comment]
ok i think im getting close but it seems a bit weird. What I want to do is compute here is a.powm(b, TWO_POW256);

```javascript
var TWO_POW256 = new BN('115792089237316195423570985008687907853269984665640564039457584007913129639936');

var a = new BN(90000);
var b = new BN(9)
var ar = a.toRed(BN.red(TWO_POW256));
 ar.redPow(b);
```

Is this correct? It looks like `red` is computing the mod of the red functions but im not sure.

**Comment by indutny** [comment]
Yeah, this is almost correct.

The result is actually `ar.redPow(b).fromRed()`. The idea is that every operation in reduction context (red) results in a number module `TWO_POW256`, so it is faster to do `redPow` with a number in a red.
