### ISSUE TITLE
Really big JS numbers don't work in the Constuctor

### ISSUE THREAD

**Issue by wanderer** [indutny/bn.js#41]
The Constructor doesn't work with  really big JS Numbers.

```
var a = new BN(8.834235323891922e+71)
a.toString(); // '0'
```

**Comment by indutny** [comment]
I'm afraid that there is implicit 52bit integer limit. `bn.js` is a library for integers and 52bits is as much as you could have in ECMA script.

**Comment by wanderer** [comment]
ok good to know, thanks again @indutny !
