### ISSUE TITLE
All inputs are valid?

### ISSUE THREAD

**Issue by ashnur** [indutny/bn.js#50]
```
var bn = require('bn.js')
var z = new bn('asd')
console.log(z instanceof bn) // true
console.log(z) // <BN: 50d>
var x = new bn(')*(&^(*&^')
console.log(x) // <BN: 3ffffffd62fcf5b>
console.log(x.toString(10)) // '-70undefined-1509797'
```

This isn't really an issue, I am just trying to understand what is happening here.
Especially the `undefined` in the `toString(10)` output seems to be interesting.

**Comment by indutny** [comment]
Heh, I'm just trying to save some time by ignoring the invalid characters. Expect garbage to be there :)

**Comment by ashnur** [comment]
That's great, but how can I know which characters are invalid?

**Comment by indutny** [comment]
By default it is base-10 so it is [0-9], if you wish to use different base - they will be different

**Comment by ashnur** [comment]
I see, thanks for the clarification.
