### ISSUE TITLE
regression in 4.1.0

### ISSUE THREAD

**Issue by calvinmetcalf** [indutny/bn.js#63]
specifically in dsa calculations, will try to make a test case, but basically browserify-sign dsa doesn't work with 4.1.0 but does with 4.0.0

**Comment by calvinmetcalf** [comment]
@indutny where does [this 26](https://github.com/indutny/bn.js/blob/1dd4cfe431392dac557e98c1d0e8610bb710092b/lib/bn.js#L2369) come from? will it possibly not work for big enough numbers?

**Comment by indutny** [comment]
@calvinmetcalf it is number of bits in a single limb. This is the same for all numbers.

**Comment by calvinmetcalf** [comment]
hm I am reliably getting a failure in sign-browserify but with the same `this.m`, a, and num get a different output from red.prototype.pow then when tested directly is there another variable i'm missing which is affecting the output?

**Comment by calvinmetcalf** [comment]
fixed
