### ISSUE TITLE
Make the `negative` property public.

### ISSUE THREAD

**Issue by axic** [indutny/bn.js#70]
Is there any particular reason why the ```negative``` property is not a public field?

In my use case, I keep numbers of variable sizes in ```BN``` and have them dumped as binary. I would like to know if they are negative, because of two's complements padding I need to add differs.

So far I was using one of three horrible shortcuts to check:
```js
return bn.toString().startsWith('-');
or
return BN.min(bn, new BN(0)) === bn;
or
return bn.abs() !== bn;
```

I am probably doing it wrong, and there's a simpler way or ```negative``` can be made public.

**Comment by indutny** [comment]
I think we need a public API method for this instead. Like `isNeg()`.

Could you be interested in contributing this feature and documentation (in README)?

Thanks!

**Comment by axic** [comment]
I can do a pull request, along the lines of this? (to follow your coding style)

```
BN.isNeg = function isNeg() {
  return this.negative;
}
```

And the README + tests.

**Comment by indutny** [comment]
Yep, looks perfect!

**Comment by indutny** [comment]
Actually, wait... Let's do `this.negative !== 0`, ok?

**Comment by axic** [comment]
Done: https://github.com/indutny/bn.js/pull/71
