### ISSUE TITLE
Feature request: bitwise negation

### ISSUE THREAD

**Issue by axic** [indutny/bn.js#72]
It would be nice to have a method for doing bitwise negation.

**Comment by indutny** [comment]
Example?

**Comment by axic** [comment]
```a.not()``` and ```a.inot()``` - bitwise negate (NOT) all bits (up to bitLength())

**Comment by axic** [comment]
Perhaps it there should be two versions: ```a.not()``` would negative up to ```a.bitLength()```, but ```a.notn(b)``` would also include all the leading zeroes (and set them to 1), where the number of leading zeroes equal to ```b - a.bitLength()```.

Assuming a.bitLength() equals to the position of the most significant bit set.

**Comment by indutny** [comment]
So basically `a.not().not()` will not be equal to `a`?

**Comment by axic** [comment]
Correct, it wouldn't. Not sure ```a.not()``` is the right one to have. I am interested in having ```a.notn(b)```.

**Comment by indutny** [comment]
@axic what is your use case?

**Comment by axic** [comment]
My actual use case was https://github.com/indutny/bn.js/issues/73, but have done it differently since. I cannot think about any use case top of my head, but my hunch is it can be useful in the future.

That being said, I'm not interested in implementing it. Perhaps this issue can stay open until someone does it.

**Comment by axic** [comment]
Meanwhile my API suggestion for this would be:
- ```inotn(width)```
- ```notn(width)```
- ```inot()``` - where bitLength() is used as width
- ```not()``` - where bitLength() is used as width

So that ```a.inotn(256).inotn(256) === a```, but ```a.inot().inot()``` might differ.

If it is an intent to avoid user error, ```inot()``` and ```not()``` should not be added.

I have also created sample implementations and will create pull requests.

**Comment by axic** [comment]
PR https://github.com/indutny/bn.js/pull/77 was merged, this is done.
