### ISSUE TITLE
handling zero on sub bug

### ISSUE THREAD

**Issue by wanderer** [indutny/bn.js#82]
This is not what I expected
`new BN(0).divn(100000).subn(2)`
`<BN: 3fffffe>`

I would think it would just be `-2`

**Comment by indutny** [comment]
I'm sorry, but `subn` does not support sign change :( Can't say if it is intended or not, perhaps just a documentation bug.

Though, if you have an idea on how to add support for sign change for both (`addn` and `subn`) whilst keeping the speed of current implementation - please let me know!

**Comment by axic** [comment]
It should throw an assert in that case as the rest of the functions do - shouldnt it?

**Comment by wanderer** [comment]
should be fixed now
