### ISSUE TITLE
Bug in parseBase for numbers containing a dot ('0.0079')

### ISSUE THREAD

**Issue by axic** [indutny/bn.js#90]
``` js
new BN('0.0079', 10) // <BN: ffffb22f>
new BN('0.02', 10) // <BN: ffffff3a>
```

`_init`, `parseBase` or `_parseBase` will not care if a dot is included in a base-10 input, will process it as `('.' - 48) & 0xf`.

I think it should just reject such input?

**Comment by axic** [comment]
The same applies to ```parseHex``` (as basically it is the same code as ```parseBase```, with one exception: range is limited to f/F).

```js
new BN('1234', 16) // <BN: 1234>
new BN('12.34', 16) // <BN: 12e34>
```

**Comment by indutny** [comment]
I know that it should throw, but it doesn't right now. The thing is that this is an big __integer__ library, so you should not really pass data like this to it.

**Comment by axic** [comment]
I do know that and I don't pass those kind of numbers. However, users of my library are. I can either do pre-processing there which is quite big of an overhead. I would prefer bn.js to throw, I have the PR ready, will submit it soon - it is quite small.

**Comment by axic** [comment]
A note on the *integer* side, the library's name is short for big number and doesn't specifically mentions anywhere it is integers and not decimals. I know that, but it is not clear from the first sight at the README, maybe it should be updated.

**Comment by indutny** [comment]
Yeah, I totally agree. It should be updated. Thanks!

**Comment by fanatid** [comment]
`new BN(4.2)` return `<BN: 4>`
also should be assert here

**Comment by dcousens** [comment]
A note was added to the README at some point: `Note: decimals are not supported in this library.`

**Comment by indutny** [comment]
It throws now.
