### ISSUE TITLE
Improve smallMulTo?

### ISSUE THREAD

**Issue by fanatid** [indutny/bn.js#92]
[smallMulTo](https://github.com/indutny/bn.js/blob/6d44452a895a5063506a493a85ec205fe9dcaf61/lib/bn.js#L987)
If I understand all correctly,
```js
      var r = a * b;

      var lo = r & 0x3ffffff;
      ncarry = (ncarry + ((r / 0x4000000) | 0)) | 0;
      lo = (lo + rword) | 0;
      rword = lo & 0x3ffffff;
      ncarry = (ncarry + (lo >>> 26)) | 0;
```
can be represented as
```js
      var r = a * b + rword;
      ncarry += (r / 0x4000000) | 0;
      rword = r & 0x3ffffff;
```
2add + 1div + 1round + 1and
instead
3add + 1div + 1 round + 2and + 1shift

**Comment by indutny** [comment]
Does it work on `0x3ffffff` as both `a` and `b`?

**Comment by fanatid** [comment]
Do you mean `(0x3ffffff * 0x3ffffff + 0x3ffffff) & 0x3ffffff`?
```js
> (0x3ffffff * 0x3ffffff + 0x3ffffff + 1) & 0x3ffffff
1
> (0x3ffffff * 0x3ffffff + 0x3ffffff - 1) & 0x3ffffff
67108863
```

**Comment by indutny** [comment]
Ah, it looks like you are actually right, and this can be done! May I ask you send a PR?
