### ISSUE TITLE
mod.neg in divmod

### ISSUE THREAD

**Issue by fanatid** [indutny/bn.js#96]
https://github.com/indutny/bn.js/blob/c9d5ab8106d27c95c0e00c5651603bd35b279938/lib/bn.js#L2294
```js
if (mode !== 'div') {
  mod = res.mod.neg();
  if (positive && mod.neg) {
    mod = mod.add(num);
  }
}
```
`neg`? Will be always `true`, because `neg` is function.

**Comment by indutny** [comment]
I guess it should be `sign`. Thank you for catching this!

Could you be interested in submitting a PR with a fix and test case for this?

**Comment by indutny** [comment]
Or `negative`, whatever we have now.

**Comment by axic** [comment]
@fanatid there is a second occurrence down the line: https://github.com/indutny/bn.js/blob/c9d5ab8106d27c95c0e00c5651603bd35b279938/lib/bn.js#L2320

**Comment by axic** [comment]
Also shouldn't it be changed to `mod.iadd(num)`?

**Comment by fanatid** [comment]
@axic thanks for note! yep, mod.iadd(num) is better, I think we also can change .neg() to .negative ^= 1
